--- 
inherit_gem: 
  bixby: bixby_default.yml
AllCops: 
  Exclude: 
    - db/**/*
    - script/**/*
    - vendor/**/*
    - tmp/**/*
Metrics/BlockLength: 
  Exclude: 
    - config/**/*
    - app/controllers/catalog_controller.rb
    - spec/**/*
    - app/models/concerns/tufts/**/*
    - lib/tasks/**/*
Metrics/ClassLength: 
  Exclude: 
    - app/controllers/catalog_controller.rb
    - app/presenters/hyrax/work_show_presenter.rb
    - lib/tufts/populate_fixtures.rb
Lint/HandleExceptions:
  Exclude:
    - lib/tufts/populate_fixtures.rb
Metrics/AbcSize:
  Exclude:
    - lib/tufts/populate_fixtures.rb
Metrics/MethodLength:
  Exclude:
    - lib/tufts/populate_fixtures.rb
Performance/StringReplacement: 
  Exclude: 
    - app/controllers/tufts/works_controller.rb
RSpec/MessageSpies: 
  Enabled: false
RSpec/MultipleExpectations: 
  Exclude: 
    - spec/features/**/*
    - spec/jobs/**/*
    - spec/services/**/*
RSpec/NestedGroups: 
  Max: 4
Style/FileName: 
  Exclude: 
    - "**/Gemfile"
    - "**/*.rake"
