--- 
inherit_gem: 
  bixby: bixby_default.yml
AllCops: 
  Exclude: 
    - db/**/*
    - script/**/*
    - vendor/**/*
    - tmp/**/*
Metrics/BlockLength: 
  Exclude: 
    - config/**/*
    - app/controllers/catalog_controller.rb
    - spec/**/*
    - app/models/concerns/tufts/**/*
    - lib/tasks/**/*
    - app/helpers/eads_helper.rb
    - app/helpers/rcrs_helper.rb
    - app/models/datastreams/ead.rb
    - app/models/datastreams/rcr.rb
Metrics/BlockNesting:
  Exclude:
    - app/helpers/eads_helper.rb
Metrics/LineLength:
  Exclude: 
    - lib/tufts/populate_fixtures.rb
    - config/sitemap.rb
    - app/helpers/eads_helper.rb
    - spec/features/ead_spec.rb
    - spec/features/rcr_spec.rb
Metrics/ClassLength: 
  Exclude:
    - app/controllers/catalog_controller.rb
    - app/presenters/hyrax/work_show_presenter.rb
    - lib/tufts/populate_fixtures.rb
    - app/models/datastreams/ead.rb
Metrics/CyclomaticComplexity:
  Exclude:
    - app/controllers/concerns/with_eads.rb
    - app/controllers/concerns/with_rcrs.rb
    - app/helpers/eads_helper.rb
    - lib/tufts/populate_fixtures.rb
Metrics/PerceivedComplexity:
  Exclude:
    - app/helpers/eads_helper.rb
    - app/helpers/rcrs_helper.rb
Lint/HandleExceptions:
  Exclude:
    - lib/tufts/populate_fixtures.rb
    - lib/pid_methods.rb
Metrics/AbcSize:
  Exclude:
    - app/helpers/eads_helper.rb
    - app/helpers/rcrs_helper.rb
    - lib/tufts/populate_fixtures.rb
Metrics/MethodLength:
  Exclude:
    - app/controllers/concerns/with_rcrs.rb
    - app/helpers/eads_helper.rb
    - app/helpers/rcrs_helper.rb
    - lib/pid_methods.rb
    - lib/metadata_methods.rb
    - lib/tufts/populate_fixtures.rb
Metrics/ModuleLength:
  Exclude:
    - app/helpers/eads_helper.rb
Naming/VariableNumber:
  Exclude:
    - spec/factories/ead.rb
    - spec/factories/rcr.rb
Performance/StringReplacement: 
  Exclude: 
    - app/controllers/tufts/works_controller.rb
Rails/FilePath:
  Exclude:
    - spec/factories/ead.rb
    - spec/factories/rcr.rb
    - spec/support/ldap_manager.rb
RSpec/ExampleLength:
  Exclude:
    - spec/features/ead_spec.rb
    - spec/features/rcr_spec.rb
RSpec/MessageSpies: 
  Enabled: false
RSpec/MultipleExpectations: 
  Exclude: 
    - spec/features/**/*
    - spec/jobs/**/*
    - spec/services/**/*
RSpec/NestedGroups: 
  Max: 4
RSpec/VerifiedDoubles:
  Exclude:
    - spec/models/**/*
Style/FileName: 
  Exclude: 
    - "**/Gemfile"
    - "**/*.rake"
Style/GuardClause:
  Exclude:
    - app/controllers/concerns/with_rcrs.rb
    - spec/support/ldap_manager.rb
Style/NestedTernaryOperator:
  Exclude:
    - app/helpers/eads_helper.rb
Style/Next:
  Exclude:
    - app/helpers/eads_helper.rb
Style/NumericPredicate:
  Exclude:
    - app/helpers/eads_helper.rb
