---
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  Exclude:
    - db/**/*
    - script/**/*
    - vendor/**/*
    - tmp/**/*
    - lib/tufts/tei_parser.rb
    - lib/tufts/tei_toc.rb
    - lib/tufts/tei_constraints.rb
    - app/controllers/gallery_controller.rb
    - app/helpers/characterization.rb
    - lib/pid_methods.rb
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - app/controllers/catalog_controller.rb
    - app/controllers/concerns/with_transcripts.rb
    - spec/**/*
    - app/models/concerns/tufts/**/*
    - lib/tasks/**/*
    - app/helpers/eads_helper.rb
    - app/helpers/rcrs_helper.rb
    - app/helpers/transcripts_helper.rb
    - app/models/datastreams/ead.rb
    - app/models/datastreams/rcr.rb
    - app/models/datastreams/tei.rb
    - app/models/transcript_chunk.rb
Metrics/BlockNesting:
  Exclude:
    - app/helpers/eads_helper.rb
Layout/IndentationConsistency: #this one
  EnforcedStyle: indented_internal_methods
Layout/LineLength:
  Exclude:
    - lib/tufts/populate_fixtures.rb
    - config/sitemap.rb
    - app/helpers/eads_helper.rb
    - app/helpers/transcripts_helper.rb
    - spec/features/ead_spec.rb
    - spec/features/rcr_spec.rb
    - config/initializers/assets.rb
    - lib/metadata_methods.rb
Metrics/ClassLength:
  Exclude:
    - app/controllers/catalog_controller.rb
    - app/presenters/hyrax/work_show_presenter.rb
    - lib/tufts/populate_fixtures.rb
    - app/models/datastreams/ead.rb
    - app/models/transcript_chunk.rb
Metrics/CyclomaticComplexity:
  Exclude:
    - app/controllers/concerns/with_eads.rb
    - app/controllers/concerns/with_rcrs.rb
    - app/controllers/concerns/with_transcripts.rb
    - app/helpers/eads_helper.rb
    - app/helpers/transcripts_helper.rb
    - app/models/transcript_chunk.rb
    - lib/tufts/populate_fixtures.rb
    - lib/pid_methods.rb
    - app/controllers/concerns/with_teis.rb
Metrics/PerceivedComplexity:
  Exclude:
    - app/controllers/concerns/with_transcripts.rb
    - app/helpers/eads_helper.rb
    - app/helpers/rcrs_helper.rb
    - app/helpers/transcripts_helper.rb
    - app/models/transcript_chunk.rb
    - lib/tufts/populate_fixtures.rb
Lint/SuppressedException:
  Exclude:
    - lib/tufts/populate_fixtures.rb
    - lib/pid_methods.rb
Metrics/AbcSize:
  Exclude:
    - app/controllers/concerns/with_transcripts.rb
    - app/helpers/eads_helper.rb
    - app/helpers/rcrs_helper.rb
    - app/helpers/transcripts_helper.rb
    - app/models/transcript_chunk.rb
    - lib/tufts/populate_fixtures.rb
    - lib/pid_methods.rb
    - app/helpers/hyrax_helper.rb
Metrics/MethodLength:
  Exclude:
    - app/controllers/concerns/with_rcrs.rb
    - app/controllers/concerns/with_transcripts.rb
    - app/helpers/eads_helper.rb
    - app/helpers/rcrs_helper.rb
    - app/helpers/transcripts_helper.rb
    - app/models/transcript_chunk.rb
    - lib/pid_methods.rb
    - lib/metadata_methods.rb
    - lib/tufts/populate_fixtures.rb
Metrics/ModuleLength:
  Exclude:
    - app/helpers/eads_helper.rb
    - app/helpers/transcripts_helper.rb
    - app/helpers/hyrax_helper.rb
Naming/AccessorMethodName:
  Exclude:
    - app/models/transcript_chunk.rb
Naming/PredicateName:
  Exclude:
    - app/presenters/hyrax/generic_work_presenter.rb
Naming/VariableNumber:
  Exclude:
    - spec/factories/ead.rb
    - spec/factories/rcr.rb
Performance/StringReplacement:
  Exclude:
    - app/controllers/tufts/works_controller.rb
Rails/FilePath:
  Exclude:
    - spec/factories/ead.rb
    - spec/factories/rcr.rb
    - spec/support/ldap_manager.rb
Rails/UnknownEnv: #disabled temporarily, as rubocop is having an issue with this cop
  Exclude:
    - app/controllers/catalog_controller.rb
    - config/initializers/riiif.rb
RSpec/ExampleLength:
  Exclude:
    - spec/features/ead_spec.rb
    - spec/features/rcr_spec.rb
RSpec/InstanceVariable: # this one
  Exclude:
    - spec/features/search_results_spec.rb
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*
    - spec/jobs/**/*
    - spec/services/**/*
RSpec/NestedGroups:
  Max: 4
RSpec/VerifiedDoubles:
  Exclude:
    - spec/models/**/*
Naming/FileName:
  Exclude:
    - "**/Gemfile"
    - "**/*.rake"
Style/GuardClause:
  Exclude:
    - app/controllers/concerns/with_rcrs.rb
    - spec/support/ldap_manager.rb
Style/NestedTernaryOperator:
  Exclude:
    - app/helpers/eads_helper.rb
    - app/helpers/transcripts_helper.rb
Style/Next:
  Exclude:
    - app/helpers/eads_helper.rb
Style/NumericPredicate:
  Enabled: false
