inherit_gem:
  bixby: bixby_default.yml
AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods # Requires indentation after private and protected
Metrics/AbcSize:
  Exclude:
    - app/helpers/eads_helper.rb
    - app/helpers/transcripts_helper.rb
    - app/models/transcript_chunk.rb
    - lib/tufts/populate_fixtures.rb
    - lib/tufts/tei_parser.rb
    - lib/tufts/tei_toc.rb
Metrics/BlockLength:
  Exclude:
    - app/controllers/catalog_controller.rb
    - app/helpers/eads_helper.rb
    - app/helpers/transcripts_helper.rb
    - app/models/datastreams/*
    - config/**/*
    - lib/tasks/**/*
    - lib/tufts/tei_parser.rb
    - spec/**/*
  Max: 30 # Many blocks are like 27 lines long. 30 vs 25, not a huge difference.
Metrics/BlockNesting:
  Exclude:
    - app/helpers/eads_helper.rb
    - lib/tufts/tei_parser.rb
Style/FrozenStringLiteralComment:
  Exclude:
    - app/helpers/transcripts_helper.rb
Metrics/ClassLength:
  Exclude:
    - app/controllers/catalog_controller.rb
    - app/models/datastreams/ead.rb
    - app/models/transcript_chunk.rb
    - lib/tufts/populate_fixtures.rb
Metrics/CyclomaticComplexity:
  Exclude:
    - app/helpers/eads_helper.rb
    - app/helpers/transcripts_helper.rb
    - app/models/transcript_chunk.rb
    - lib/tufts/populate_fixtures.rb
    - lib/tufts/tei_parser.rb
    - lib/tufts/tei_toc.rb
Metrics/MethodLength:
  Exclude:
    - app/helpers/eads_helper.rb
    - app/helpers/transcripts_helper.rb
    - app/models/transcript_chunk.rb
    - lib/tufts/populate_fixtures.rb
    - lib/tufts/tei_parser.rb
    - lib/tufts/tei_toc.rb
  Max: 20 # A little less strict to make our lives easier.
Metrics/ModuleLength:
  Exclude:
    - app/helpers/eads_helper.rb
    - app/helpers/hyrax_helper.rb
    - app/helpers/transcripts_helper.rb
    - lib/tufts/tei_parser.rb
Metrics/PerceivedComplexity:
  Exclude:
    - app/helpers/eads_helper.rb
    - app/helpers/transcripts_helper.rb
    - app/models/transcript_chunk.rb
    - lib/tufts/populate_fixtures.rb
    - lib/tufts/tei_parser.rb
    - lib/tufts/tei_toc.rb
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - stage
RSpec/ExampleLength:
  Exclude:
    - spec/features/ead_spec.rb
    - spec/features/rcr_spec.rb
RSpec/InstanceVariable:
  Exclude:
    - spec/features/search_results_spec.rb
RSpec/MultipleExpectations:
  Enabled: false
