language: ruby
sudo: required
cache: bundler
dist: trusty

jdk:
  - oraclejdk8
rvm:
  - 2.3.4
before_script:
  - cp config/fedora.yml.sample config/fedora.yml
  - cp config/solr.yml.sample config/solr.yml
  - cp config/devise.yml.sample config/devise.yml
  - cp config/database.yml.sample config/database.yml
  - cp config/blacklight.yml.sample config/blacklight.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - bundle exec rake db:create
script:
  - bundle exec rubocop
  - bundle exec rake travis
addons:
  apt:
    packages:
     - imagemagick
services:
  - redis-server
notifications:
  email: tdl-commiters@googlegroups.com
