version: '3'

networks:
  external:
    name: external-network
    external: true
  internal:
    name: internal-network
    external: true

volumes:
  db-dev:
  fcrepo-dev:
  solr-dev:
  redis-dev:
  bundled:

services:
  ##
  # Basic Rails application build image
  tdl-app: &tdl-app
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - .:/data # mount current directory into the image
      - bundled:/usr/local/bundle
    networks:
      external:
      internal:
    # use tmpfs for tmp and log for performance and to allow
    # multiple builds in parallel. Both directories are mounted
    # into the image AFTER the working directory is mounted.
    tmpfs:
      - /data/log

  ##
  # Development environment for application
  tdl-dev: &tdl-dev
    <<: *tdl-app
    environment:
      - CACHE_PATH=/data/tmp/uploads/cache
      - DB_NAME=development
      - DB_HOST=tdl-db-dev
      - DB_PASSWORD=postgres
      - DB_PORT='3306'
      - DB_USERNAME=postgres
      - DERIVATIVES_PATH=/data/tmp/derivatives
      - FEDORA_URL=http://fcrepo-dev:8080/rest
      - FITS_PATH=/opt/fits-1.0.5/fits.sh
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
      - SECRET_KEY_BASE=bobross
      - SOLR_URL=http://solr-dev:8983/solr/development
      - UPLOADS_PATH=/data/tmp/uploads
    depends_on:
      - tdl-db-dev
    expose:
      - 4000
  server:
    <<: *tdl-dev
    command: >
      bash -c "./build/entrypoint.sh &&
      bundle exec rails s -p 4000 -b '0.0.0.0'"
  ##
  # Test environment for application
  test: &tdl-test
    <<: *tdl-app
    environment:
      - CACHE_PATH=/data/tmp/uploads/cache
      - IN_DOCKER=true
      - HUB_URL=http://chrome:4444/wd/hub
      - DB_NAME=test
      - DB_HOST=tdl-db-test
      - DB_PASSWORD=postgres
      - DB_PORT='3306'
      - DB_USERNAME=postgres
      - DERIVATIVES_PATH=/data/tmp/derivatives
      - FEDORA_URL=http://fcrepo-test:8080/rest
      - FITS_PATH=/opt/fits-1.0.5/fits.sh
      - RAILS_ENV=test
      - REDIS_HOST=redis-test
      - REDIS_PORT=6379
      - SECRET_KEY_BASE=bobross
      - SOLR_URL=http://solr-test:8983/solr/test
      - UPLOADS_PATH=/data/tmp/uploads
    depends_on:
      - tdl-db-test
    volumes:
      - .:/data # mount current directory into the image
      - ./tmp:/tmp
      - bundled:/usr/local/bundle
    command: >
      bash -c "./build/entrypoint.sh &&
      puma -b tcp://0.0.0.0:4001 -e test"
    expose:
      - 4001
##
  # Mariadb database server
  db: &db
    image: mariadb:10
    networks:
      internal:
  tdl-db-dev:
    <<: *db
    environment:
      - MYSQL_DATABASE=development
      - MYSQL_USER=postgres
      - MYSQL_PASSWORD=postgres
      - MYSQL_ROOT_PASSWORD=postgres
    ports:
      - 3307:3307
    volumes:
      - db-dev:/var/lib/mysql
  tdl-db-test:
    <<: *db
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=postgres
      - MYSQL_PASSWORD=postgres
      - MYSQL_ROOT_PASSWORD=postgres
    ports:
      - 3308:3308
    tmpfs: /var/lib/mysql
